# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WeChat
  
pod 'FMDB', '~> 2.6.2'
pod 'MBProgressHUD', '~> 0.9'
pod 'SDWebImage', '~> 3.7'
pod 'MJRefresh', '~> 3.1.12'
pod 'MWPhotoBrowser', '~> 2.1.2'
end
